### ISSUE TITLE
ASL Script for TMUF

### ISSUE THREAD

**Issue by SmokyBird** [NeKzor/ASL-Scripts#1]
Hellow there,

is there any scripts being created for TMUF actually? Would love to use it to make some speedruns about it, it's been a long time.

Thanks in advance for the answer!

**Comment by NeKzor** [comment]
Currently don't have any time for this but we'll see. You can always try to make one yourself, just learn from the [ASL-Documentation](https://github.com/LiveSplit/LiveSplit/blob/master/Documentation/Auto-Splitters.md).
